### ISSUE TITLE
Name Change

### ISSUE THREAD

**Issue by Kemoke** [dreamstalker/rehlds#77]
The server will change player names seemingly at random for about 5 minutes after start then it will be fine after.
Also is there some way to increase the string ban limit. Some players are getting banned for using buyscripts.

**Comment by theAsmodai** [comment]
1) What nickname becomes after the change?
2) Try this cvars:
sv_rehlds_stringcmdrate_max_avg 64
sv_rehlds_stringcmdrate_max_burst 100

**Comment by Kemoke** [comment]
It cuts off 2-3 letters

**Comment by theAsmodai** [comment]
Where do you see the cut nicknames? Could this be due to unicode characters? I need more information how to reproduce this bug.

**Comment by Kemoke** [comment]
I dont  really know how to reproduce. Just now one of players had his name reverted to the old one. The nicknames are literally changed, x has changed his name to y(in scoreboard you can see changed), but in console you see your old name.

**Comment by s1lentq** [comment]
you can try last build rehlds, maybe this issue was solved.

**Comment by Kemoke** [comment]
It seems like its fixed now thanks.

**Comment by Infamous2017** [comment]
This Problem is still there !!!!    in last REHLDS . Pls fix.
