### ISSUE TITLE
Banned for move commands flooding (burst)

### ISSUE THREAD

**Issue by Maxpain177** [dreamstalker/rehlds#89]
Hi. I tried to install rehlds on several servers on fastcup.net, but servers are banned some players with reason "Banned for move commands flooding (burst)"

Current settings:
sv_maxupdaterate 102
sv_minupdaterate 102
sv_maxrate 100000
sv_minrate 100000
sys_ticrate 1060

Rehlds build: 563

**Comment by coolmans** [comment]
I was the same, disable plugins that check client on Alias

**Comment by Maxpain177** [comment]
meta list
Currently loaded plugins:
      description      stat pend  file              vers      src  load  unlod
 [ 1] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.8.3-d  ini  Start ANY
 [ 2] WHBlocker        RUN   -    whblocker_mm_i38  v1.5.620  ini  Chlvl ANY
 [ 3] CStrike          RUN   -    cstrike_amxx_i38  v1.8.3-d  pl1  ANY   ANY
 [ 4] FakeMeta         RUN   -    fakemeta_amxx_i3  v1.8.3-d  pl1  ANY   ANY
 [ 5] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.8.3-d  pl1  ANY   ANY
5 plugins, 5 running

amxx plugins
Currently loaded plugins:
       name                    version     author            file             status
 [  1] Anti DD Scroll          1.0         Empower           anti_dd_scroll.  running
 [  2] Block Spawn For Reconn  0.3         Bos93, Subb98     antireconnect.a  running
 [  3] Teammate money          1.1.0       Maxpain           teammate_money.  running
 [  4] Voices Management       1.0.0       Maxpain           voices_manageme  running
 [  5] Bomb has been defused   1.1         xPaw              bomb_def_sound.  running
 [  6] Accuracy Fix            3.0         Numb              accuracy_fix.am  running
 [  7] Spray fix               1.0.0       Maxpain           spray_fix.amxx   running
 [  8] FASTCUP.NET [TV]        0.0.1       Maxpain           fastcup_tv.amxx  running
 [  9] Fix AutoBuy&Smoke Bug   1.3         dr.aft & others   autobuy_block.a  running
9 plugins, 9 running

**Comment by coolmans** [comment]
I think that these:
Anti DD Scroll

**Comment by latinas** [comment]
Disable anti dd scroll and observe the server again

**Comment by Maxpain177** [comment]
thx :)

**Comment by Sylvert0** [comment]
Check the cvars in https://github.com/dreamstalker/rehlds/blob/14890276de0488472226efbea64f094118162da6/rehlds/rehlds/rehlds_security.cpp

**Comment by mforce95** [comment]
sv_rehlds_movecmdrate_max_avg 1500 solved the problem for me.

**Comment by IgnacioFDM** [comment]
Can confirm that with default values normal players get this a lot.

**Comment by OZone998** [comment]
Yep, on my server many players get this ban quite often.
I have no plugins that check/change player aliases.
I think that there have to be some improvement.

**Comment by theAsmodai** [comment]
Please post exact logs with bans.

**Comment by OZone998** [comment]
It's "addip" ban, so I didn't found any logs.
Today two of my admins where banned in nearly exact moment
- they were playing for more than an hour and then they have been banned.
All I can say that players get ban only for "Banned for move commands flooding (burst)", 
three other functions seems to work normal, there are anomalies only in CheckBurstRate.

Oh, and I forgot to post my server's settings:
sv_maxrate "25000"
sv_minrate "10000"
sv_maxupdaterate "111"
sv_minupdaterate "33" 
sys_tickrate "300"
ReHLDS Build: 624

**Comment by OZone998** [comment]
Well, something is really wrong - several bans in the same moment (logs from server console):
Dropped Alcaponek from server
Reason:  Banned for move commands flooding (burst)
Dropped Tomekbombel from server
Reason:  Banned for move commands flooding (burst)
Dropped SolMonterSolGoodxD from server
Reason:  Banned for move commands flooding (burst)
Dropped Ola ;* from server
Reason:  Banned for move commands flooding (burst)

Less than 5 minutes later:
Dropped straznik VP from server
Reason:  Banned for move commands flooding (burst)
Dropped Anakonda from server
Reason:  Banned for move commands flooding (burst)
Dropped zolty from server
Reason:  Banned for move commands flooding (burst)
Dropped BadWo from server
Reason:  Banned for move commands flooding (burst)

**Comment by mforce95** [comment]
sv_rehlds_movecmdrate_max_avg 1500
sv_rehlds_movecmdrate_max_burst 3000

It's perfect for me but when somebody lose the connection, got banned and invisible spawned and alive...

**Comment by fcastro16** [comment]
I set those two commands and the issue still happens.
Any fix?

**Comment by IgnacioFDM** [comment]
Here you go

sv_rehlds_movecmdrate_max_burst -1
sv_rehlds_stringcmdrate_max_burst -1

**Comment by Maxpain177** [comment]
Fixed

**Comment by lucasdearaujo** [comment]
The issue still there. I've got the same problem yesterday when a user had a delay on this connection.

**Comment by Nemesis31** [comment]
Hi, same here: https://cs.team-shk.fr/index.php?file=Forum&page=viewtopic&forum_id=2&thread_id=3403#20372

**Comment by ServersBR** [comment]
sv_rehlds_movecmdrate_max_avg -1
sv_rehlds_movecmdrate_max_burst -1

**Comment by Nur9912** [comment]
> Here you go
> 
> sv_rehlds_movecmdrate_max_burst -1 
sv_rehlds_stringcmdrate_max_burst -1
how to do this, tell me more
